name: rce-test
on:
  workflow_dispatch:
    inputs:
      variable:
        description: The RCE command to execute
        default: '"; YOUR_COMMAND # '
  issues:
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:
  rce-test:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event_name == 'issues' }}
        run: |
          echo "${{ github.event.issue.title }}"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
          MY_GITHUB_TOKEN: ${{ github.token }}
      - if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "${{ github.event.pull_request.title }}"
      - if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "${{ github.event.inputs.variable }}"
