name: rce-test
on:
  workflow_dispatch:
    inputs:
      variable:
        description: The RCE command to execute
        default: '"; YOUR_COMMAND # '
  issues:
    type: labeled
  pull_request:

jobs:
  rce-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test"
